---
- set_fact: apache_daemon_name=httpd
- set_fact: wordpress_db_user=secret_user_name
- set_fact: wordpress_db_password=f447b20a7fcbf53a5d5be013ea0b15af
- set_fact: wordpress_db_name=secret_db

- name: install php
  yum: name={{item}}
  with_items:
    - php
    - php-mysql

- name: download wordpress packaged file
  command: wget -c --no-check-certificate -O /opt/wordpress.tar.gz "http://wordpress.org/latest.tar.gz"

- name: uncompress wordpress
  command: sudo tar xvzf /opt/wordpress.tar.gz -C /var/www/html --strip 1

- name: set proper permission to wordpress
  file: path=/var/www/html/ owner=apache group=apache recurse=yes state=directory

- name: set wordpress config file
  template: src=wp-config.php  dest=/opt/wordpress/wp-config.php owner=apache group=apache

- name: create log file directory
  file: path=/var/logs/wordpress/ force=yes owner=apache group=apache state=directory

- name: create wordpress database
  command: mysql -u root -e "CREATE DATABASE IF NOT EXISTS {{wordpress_db_name}};"

- name: create db credential for wordpress
  command: mysql -u root -e "grant all on {{wordpress_db_name}}.* to '{{wordpress_db_user}}'@'localhost' identified by '{{wordpress_db_password}}';"
